from datetime import datetime
from database import db

class User(db.Model):
    __tablename__ = 'user'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    civility_id = db.Column(db.Integer, nullable=False)
    photo = db.Column(db.String(255), nullable=True)
    country_id = db.Column(db.Integer, nullable=True)
    laboratory_id = db.Column(db.Integer, nullable=False)
    division_id = db.Column(db.Integer, nullable=True)
    team_id = db.Column(db.Integer, nullable=True)
    create_user_id = db.Column(db.Integer, nullable=True)
    update_user_id = db.Column(db.Integer, nullable=True)
    username = db.Column(db.String(180), nullable=False, unique=True)
    username_canonical = db.Column(db.String(180), nullable=False, unique=True)
    email = db.Column(db.String(180), nullable=False, unique=True)
    email_canonical = db.Column(db.String(180), nullable=False, unique=True)
    enabled = db.Column(db.Boolean, nullable=False, default=True)
    salt = db.Column(db.String(255), nullable=True)
    password = db.Column(db.String(255), nullable=False)
    last_login = db.Column(db.DateTime, nullable=True)
    confirmation_token = db.Column(db.String(180), nullable=True)
    password_requested_at = db.Column(db.DateTime, nullable=True)
    roles = db.Column(db.Text, nullable=False)
    photo = db.Column(db.String(255), nullable=True)
    firstname = db.Column(db.String(100), nullable=False)
    lastname = db.Column(db.String(100), nullable=False)
    address = db.Column(db.String(50), nullable=True)
    address_bis = db.Column(db.String(50), nullable=True)
    city = db.Column(db.String(50), nullable=True)
    phone = db.Column(db.String(20), nullable=True)
    zip_code = db.Column(db.String(20), nullable=True)
    function_user = db.Column(db.String(256), nullable=True)
    last_change_password = db.Column(db.DateTime, nullable=True)
    info_1 = db.Column(db.String(255), nullable=True)
    info_2 = db.Column(db.String(255), nullable=True)
    info_3 = db.Column(db.String(255), nullable=True)
    create_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    update_date = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    is_valid = db.Column(db.Boolean, nullable=False, default=True)
    revision = db.Column(db.Integer, nullable=False, default=1)
    ldap_user = db.Column(db.Boolean, nullable=False, default=False)
    user_dn = db.Column(db.String(255), nullable=True)
    hierarchy_level = db.Column(db.Integer, nullable=False, default=0)
    mail_locale_id = db.Column(db.Integer, nullable=True)
    keycloak_id = db.Column(db.String(100), nullable=True)
    noMailEndFormation = db.Column(db.Boolean, nullable=True, default=False)
    onlyLastMailOpenFormation = db.Column(db.Boolean, nullable=True, default=False)
    count_before_access_block = db.Column(db.Integer, nullable=True)
    datetime_access_block = db.Column(db.DateTime, nullable=True)
    date_attempt_fail = db.Column(db.DateTime, nullable=True)
    group_id = db.Column(db.Integer, nullable=True)
